apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms
  labels:
    app: tms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tms
  template:
    metadata:
      labels:
        app: tms
    spec:
      containers:
        - name: tms-ui
          image: marcosperanza79/tms-ui:1
          env:
            - name: TMS_SERVICES
              value: "http://localhost:8080"
          ports:
            - containerPort: 80

        - name: tms
          image: marcosperanza79/tms:1
          ports:
            - containerPort: 8080
