logging:
  level: INFO
  loggers:
    com.oracle.interview: DEBUG
    org.hibernate.SQL:
      level: DEBUG

# Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:./target/db

server:
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080

swagger:
  resourcePackage: com.oracle.interview.resources
