version: "3.7"

# Compose file for dev and test.
# Needs marcosperanza79/tms and marcosperanza79/tms-ui images
# It includes performance tests

services:
  # The server docker image: please see https://github.com/marcosperanza/tms
  tms:
    image: marcosperanza79/tms:latest
    expose:
     - 8080

  # The UI docker image: please see https://github.com/marcosperanza/tms-ui
  tms-ui:
    image: marcosperanza79/tms-ui:latest
    environment:
      - TMS_SERVICES=http://tms:8080
    ports:
      - "80:80"

  # Uses SRC env variable for mounting a volume that point to the project codebase:
  # Needed for:
  #    wait-for-it.sh
  #    test-plan.jmx
  #    all output reports and logs
  rest-perf:
    image: justb4/jmeter
    depends_on:
      - tms
    volumes:
      - ${SRC}:/src
    entrypoint: /src/src/main/docker/wait-for-it.sh -t 0 tms:8080 -- /entrypoint.sh -JTARGET_HOST=tms -JTARGET_PORT=8080 -JTARGET_PATH=/activity -n -t /src/src/test/jmeter/test-plan.jmx -l /src/target/jmeter/test-plan.jtl -j /src/target/jmeter/jmeter.log -e -o /src/target/jmeter/report

