version: "3.7"

# Compose file for production.
# Needs marcosperanza79/tms and marcosperanza79/tms-ui images

services:
  # The server docker image: please see https://github.com/marcosperanza/tms
  tms:
    image: marcosperanza79/tms:test

    env_file:
      - env.prod
    expose:
      - 8080

  # The UI docker image: please see https://github.com/marcosperanza/tms-ui
  tms-ui:
    image: marcosperanza79/tms-ui
    environment:
      - TMS_SERVICES=http://tms:8080
    ports:
      - "80:80"

