version: "3.7"

# Compose file for production.
# Needs marcosperanza79/tms and marcosperanza79/tms-ui images

services:
  tms:
    image: marcosperanza79/tms:1
    expose:
     - 8080

  tms-ui:
    image: marcosperanza79/tms-ui:1
    environment:
      - TMS_SERVICES=http://tms:8080
    ports:
      - 80:80

